### PR TITLE
ci: add a TS ci for test build and lint

### LINKED ISSUE #39: ci: Add a CI for TypeScript code
Similar to Golang issue #38, there is no CI run on Pull Requests to check for build and Linting for incoming TypeScript code. 

Let me know if you are interested and if can I help with the addition.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Issue

Closes #39 

### Changes Proposed

Add a CI run on Pull Requests to check for build and Linting for incoming TypeScript code.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey @x-sushant-x, let me know if you need any clarification

**Comment by x-sushant-x** [comment]
I'll check this out tonight.

**Comment by x-sushant-x** [comment]
Hi @Pradumnasaraf this looks good! I'm merging it. Thanks for your contribution.

**Comment by Pradumnasaraf** [comment]
Thank you for the merge!

**Pull request merged**
