### PR TITLE
ci: add a go ci for test build and lint

### LINKED ISSUE #38: ci: Add a CI for Golang
Hey,

I noticed no CI runs on Pull Requests to check for build and Linting for incoming Golang code. 

Let me know if you are interested and if can I help with the addition.

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
### Issue

Closes #38 

### Changes Proposed

Add a CI run on Pull Requests to check for build and Linting for incoming Golang code.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey @x-sushant-x, let me know if you need any clarification

**Comment by x-sushant-x** [comment]
I'll check this out tonight.

**Comment by x-sushant-x** [comment]
Hi @Pradumnasaraf this looks good! I'm merging it. Thanks for your contribution.

**Comment by Pradumnasaraf** [comment]
Thank you for the merge!

**Pull request merged**
