### PR TITLE
Mobile view #4

### PR DESCRIPTION
**Pull request by adityarawat45**
So, this pull request is related to the mobile view design. 
-Had to remove the sidebar for small devices because the sidebar was not suitable for small devices, and added a footer instead of that.
-Changed a few things, mainly in the api configuration component's structure, and dashboard.
-Not a frontend dev, also the modifications aren't that great, it just makes sure that the app has a usable design for small devices. 

So just creating a pull request for hacktoberfest!

### CODE REVIEW

**Comment by x-sushant-x** [comment]
Hi @adityarawat45 I think you modified desktop view as well. Please make sure that you do not modify desktop view at all.


### This is your modified version
Screenshot 2024-10-09 at 7 16 18 AM

### And this is original
image

Also your mobile view do not look like as shown in issue. Please check https://github.com/x-sushant-x/Rate-Shield/issues/4 to see how I'm planning the mobile view to look like.

**Comment by adityarawat45** [comment]
Alright @x-sushant-x , thanks for the clarification related to mobile view. 
I will get back with it when the mobile view is ready.

**Comment by adityarawat45** [comment]
Hey, Could you please provide details about the .env file or a list of the required env variables?

**Comment by x-sushant-x** [comment]
Do you still wanna work on this?

**Comment by adityarawat45** [comment]
Yah, was facing issues while running the docker-compose file because of not having env file.
Need to add a few api end points to make sure the pagination and layout works fine on small view.
I'm new to open source so maybe that's why facing these issues, but will create new pull request with another branch if the layout works fine.

**Comment by x-sushant-x** [comment]
Got It! See this https://github.com/x-sushant-x/Rate-Shield/blob/main/CONTRIBUTION.md I've added structure and instructions for `.env` file.

If you still face any issue feel free to ask anytime.

**Pull request closed without merging**
